/**
 * Tutorial content displayed as a read-only overlay
 */
export const TUTORIAL_CONTENT = [
    '# MD Editor Tutorial',
    '',
    'Welcome to MD Editor — a minimal, beautiful markdown editor for macOS.',
    '',
    '## File Operations',
    '',
    'Use the **File** dropdown menu in the toolbar, or keyboard shortcuts:',
    '',
    '| Action | Shortcut |',
    '|--------|----------|',
    '| New File | ⌘N |',
    '| Open File | ⌘O |',
    '| Save | ⌘S |',
    '| Save As… | ⌘⇧S |',
    '',
    '## View Modes',
    '',
    'Switch between three view modes:',
    '',
    '| Mode | Shortcut | Description |',
    '|------|----------|-------------|',
    '| Preview | ⌘3 | Read-only rendered view |',
    '| Editor | ⌘1 | Code editing view |',
    '| Split | ⌘2 | Side-by-side editor and preview |',
    '',
    '## Font Size',
    '',
    'Adjust the preview font size for comfortable reading:',
    '',
    '- **⌘+** — Zoom in',
    '- **⌘-** — Zoom out',
    '- **⌘0** — Reset to default (14px)',
    '- Click the **size number** in the toolbar to reset',
    '',
    '## Outline Panel',
    '',
    'Click the **≡ icon** to show the outline panel.',
    '',
    '- Extracts H1~H3 headings for quick navigation',
    '- Click any heading to scroll to that position',
    '- Panel width is resizable — drag the right edge',
    '',
    '## Reading Mode',
    '',
    'Click the **⛶ icon** for distraction-free reading.',
    'Press **Esc** or click outside to exit.',
    '',
    '## Search',
    '',
    '- **Preview mode** : Click 🔍 or press ⌘F to search',
    '- **Editor mode** : Press ⌘F for Find & Replace',
    '',
    '## Recent Files',
    '',
    'Click **Recent** to see recently opened files.',
    'Files that have been moved or deleted are automatically removed.',
    '',
    '## Markdown Tips',
    '',
    '### Text Formatting',
    '',
    '**Bold** , *italic* , ~~strikethrough~~ , `inline code`',
    '',
    '> **Note:** When using bold (`**`) next to parentheses or CJK characters,',
    '> the editor automatically handles rendering.',
    '> Example: **씬(Scene)** 이 올바르게 볼드로 표시됩니다.',
    '',
    '### Table',
    '',
    '| Language | Hello |',
    '|----------|-------|',
    '| English | Hello |',
    '| 한국어 | 안녕하세요 |',
    '| 日本語 | こんにちは |',
    '',
    '### Checklist',
    '',
    '- [x] File operations (New, Open, Save)',
    '- [x] View modes (Preview, Editor, Split)',
    '- [x] Font size control',
    '- [x] Outline panel',
    '- [x] Search functionality',
    '- [x] Recent files',
    '- [ ] Write amazing content!',
    '',
    '> **Tip:** Use the **File** menu or ⌘S to save your work.',
].join('\n');
